<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mailchimp"
 *
 * Auto generated by Extension Builder 2018-02-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Powermailchimp',
	'description' => 'Adds a mailchimp finisher to powermail',
	'category' => 'plugin',
	'author' => 'DI Franz König',
	'author_email' => 'franz@koenig.digital',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);